version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - v3.1-mono

init:
- git config --global core.autocrlf true

before_build:
- dotnet --info
- choco install xunit opencover.portable codecov
- dotnet restore

build:
  project: KonSchool.sln
  verbosity: minimal
  publish_wap: true

build_script:
- dotnet build

after_build:
  - cmd: dotnet publish src\KonSchool.csproj --output %APPVEYOR_BUILD_FOLDER%\dist

artifacts:
  - path: dist

test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[KonSchool*]* -[KonSchool.Tests*]*" -output:".\KonSchool_coverage.xml" -oldstyle
- codecov -f "KonSchool_coverage.xml" -t %CODECOV_TOKEN%

deploy:
  provider: WebDeploy
  server: https://konschool.scm.azurewebsites.net:443/msdeploy.axd?site=KonSchool
  website: KonSchool
  username: $KonSchool
  password:
    secure: 1kfpmAnJMc699Y32qORP2BtyaMmdmHxVdZATVRHNV24pxDlz7MjGMzHYDwo0i9Odgw+UGJVZfzr6X+h67I1aWw==
  ntlm: false
  remove_files: false
